### ISSUE TITLE
Get the selected values

### ISSUE THREAD

**Issue by MohammadElKhatib** [arbh89/DropDownListChosen#7]
hello I am using DropDownLostChosen with ASP.Net and i am able to fill and show it but not able to get the selected values !

i am trying to use 
dropdown.SelectedIndex
dropdown.SelectedValue
dropdown.SelectedItem

in VB.net but all not working

**Comment by arbh89** [comment]
Make sure to bind the control inside IsPostBack Validation.

**Comment by MohammadElKhatib** [comment]
@arbh89 thanks for reply but still not working i am using the control same as:

<asp:DropDownListChosen ID="ddCollaboratorDistricts" runat="server"
                            NoResultsText="غير موجود..." width="206px" AllowSingleDeselect="true" multiple ="true" DataPlaceHolder="أدخل أو إختر..." RightToLeft="True" CausesValidation="True" AutoPostBack="True">
<asp:ListItem></asp:ListItem>
                        </asp:DropDownListChosen>

and after filling items and selecting i am trying to get selected items by using:

ddCollaboratorDistricts.SelectedValue 
ddCollaboratorDistricts.SelectedItem.Text 
ddCollaboratorDistricts.SelectedIndex 
ddCollaboratorDistricts.Text


but nothing work ...

**Comment by arbh89** [comment]
How are you binding the data?

**Comment by MohammadElKhatib** [comment]
I am filling the items from database on page load

sample code:

ConnectToDB_sql(SqlConn)

        Dim Operation As Boolean
        Operation = ReadData_sql(SqlConn, DS, "select Districts_NS.* from Districts_NS order by A_Name")

        If Operation = True Then
            For I = 0 To DS.Tables(0).Rows.Count - 1
                Dim LA As New ListItem
                LA.Text = DS.Tables(0).Rows(I).Item("A_Name")
                LA.Value = DS.Tables(0).Rows(I).Item("DistrictID")

                ddCollaboratorDistricts.Items.Add(LA)
            Next
        End If

        SqlConn.Close()

**Comment by arbh89** [comment]
Where is the IsPostback validation?

**Comment by MohammadElKhatib** [comment]
On Page load i am checking is post back:
FillDistricts is the function filling the dropdownlist

Protected Sub Page_Load(sender As Object, e As EventArgs) Handles Me.Load

        checkSession()

        If Not Page.IsPostBack Then
            FillCombos()
        Else
            FillDistricts()
        End If


    End Sub

**Comment by arbh89** [comment]
Are you binding data somewhere else?

Can you try the same code with a normal DropDownList, it should be the same behavior.

**Comment by MohammadElKhatib** [comment]
I am binding data inside FillCombos also.

i tried to replace it with normal DropDownList and it works normally, this is strange.

**Comment by MohammadElKhatib** [comment]
i am trying now to call ddCollaboratorDistricts_SelectedIndexChanged when changing index but it seems not working cannot catch changing selected index

**Comment by MohammadElKhatib** [comment]
I just tried to fill data manually by adding lisitems under the dropdownlist also no luck to get selected items 

by the way i am using this version:

![image](https://user-images.githubusercontent.com/5835334/46930642-e525ec00-d057-11e8-8329-e6e54de114d5.png)

if you have some sample project kindly provide it to me. thanks
